name: Publish to npm Sounds Control

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.18.0'
        registry-url: 'https://registry.npmjs.org'

    - name: Display Node.js version
      run: node -v

    - name: Display NPM version
      run: npm -v

    - name: Display TSC version
      run: tsc -v

    - name: Install dependencies
      run: npm install

    - name: Show TypeScript config
      run: tsc --showConfig

    - name: Build the package
      run: npm run build

    - name: Publish to npm
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
